#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const manifest = JSON.parse(read('manifest.json'));
const popup = read('src/popup.html');
const popupJs = read('src/popup.js');
const css = read('src/content.css');
const readme = read('README.md');
const report = JSON.parse(read('data/merge-report.json'));

assert.match(manifest.name, /[一-鿿]/);
assert.match(manifest.description, /[一-鿿]/);
assert.match(manifest.action.default_title, /[一-鿿]/);
assert.equal(manifest.manifest_version, 3);
assert.deepEqual(manifest.permissions, ['storage', 'notifications']);
assert.match(popup, /<html lang="zh-CN">/);
assert.match(popup, /本地学习只保存在这台设备，不上传账号数据/);
assert.match(popup, /id="run-everything"[\s\S]*一键签到&amp;打卡/);
assert.doesNotMatch(popup, /id="run-question"|id="run-checkin"/);
assert.doesNotMatch(popup, /打开每日答题|打开每日签到|open-question|open-checkin/);
assert.doesNotMatch(popupJs, /openPage|window\.open|无法打开/);
assert.match(readme, /10 个成功来源、1304 条 raw records、198 个 normalized entries、11 个 ambiguous entries、4 个 cross-source conflicts/);
assert.match(readme, /不接入 AI/);
assert.match(readme, /不保存 Cookie/);
assert.match(readme, /不调用旧 Firebase/);
assert.match(readme, /不绕过验证码或登录/);
assert.match(readme, /不伪造站点请求/);
assert.match(readme, /仅作个人本地使用/);
assert.match(readme, /仅申请 `storage` 和 `notifications` 权限；`notifications` 仅用于签到完成后的系统通知/);
assert.doesNotMatch(readme, /扩展只申请 `storage` 权限/);
assert.match(readme, /后台以 `active:false` 打开或复用目标标签页/);
assert.match(readme, /不会切换用户当前的 active tab/);
assert.match(readme, /显示 3 秒 Toast/);
assert.match(readme, /发送一条系统通知/);
assert.match(readme, /自动关闭目标标签页/);
assert.match(readme, /用户当前正在使用的标签页不会关闭/);
assert(readme.includes("find src scripts -type f \\( -name '*.js' -o -name '*.mjs' \\) -print0 | xargs -0 -n1 node --check"), 'README must document the portable src/scripts node --check command');
assert.match(readme, /macOS zsh/);
assert.match(readme, /覆盖 `src` 与 `scripts` 中实际存在的 `\.js` 和 `\.mjs` 文件/);
assert.doesNotMatch(readme, /src\/scripts\/\*\.js/);
assert.match(readme, new RegExp(`${report.successfulSources} 个成功来源`));
assert.match(readme, new RegExp(`${report.rawRecordCount} 条 raw records`));
assert.match(readme, new RegExp(`${report.normalizedEntryCount} 个 normalized entries`));
assert.match(readme, new RegExp(`${report.ambiguousEntryCount} 个 ambiguous entries`));
assert.match(readme, new RegExp(`${report.conflictCount} 个 cross-source conflicts`));
for (const id of ['p3a-daily-question-helper', 'p3a-daily-checkin-helper']) assert.match(css, new RegExp(`#${id}`));
assert.match(css, /min-(?:width|height):\s*44px/);
assert.match(css, /:disabled/);
assert.match(css, /:focus-visible/);
assert.match(css, /prefers-color-scheme:\s*dark/);
assert.match(css, /color-scheme:\s*dark/);
console.log('UI and documentation tests passed.');
